[package]
name = "wtm"
version = "0.1.0"
authors = ["bretzle <johnfish218@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Logging
log = "0.4.8"
fern = "0.6.0"
chrono = "0.4.11"

ctrlc = { version = "3.1.4", optional = true }
lazy_static = "1.4.0"
serde = "1.0.114"
serde_derive = "1.0.114"
dirs = "3.0.0"
toml = "0.5.6"
crossbeam-channel = "0.4"

[dependencies.winapi]
version = "0.3.9"
features = ["winuser", "impl-default", "windowsx"]


[features]
default = ["debug"]
debug = ["fern/colored", "ctrlc"]