app_bar_bg        = 2892839
app_bar_font      = "Consolas"
app_bar_font_size = 18
app_bar_height    = 20
display_app_bar   = true
launch_on_startup = false
light_theme       = false
margin            = 0
multi_monitor     = false
padding           = 0
remove_task_bar   = true
remove_title_bar  = true
work_mode         = true

[[keybindings]]
key      = "B"
modifier = "Alt"
type     = { Launch = "C:\\Program Files\\Mozilla Firefox\\firefox.exe" }

[[keybindings]]
key      = "Q"
modifier = "Alt"
type     = "CloseTile"

[[keybindings]]
key      = "X"
modifier = "Alt"
type     = "Quit"

[[keybindings]]
key      = "H"
modifier = "Alt"
type     = { Focus = "Left" }

[[keybindings]]
key      = "J"
modifier = "Alt"
type     = { Focus = "Down" }

[[keybindings]]
key      = "K"
modifier = "Alt"
type     = { Focus = "Up" }

[[keybindings]]
key      = "L"
modifier = "Alt"
type     = { Focus = "Right" }

[[keybindings]]
key      = "H"
modifier = "AltControl"
type     = { Swap = "Left" }

[[keybindings]]
key      = "J"
modifier = "AltControl"
type     = { Swap = "Down" }

[[keybindings]]
key      = "K"
modifier = "AltControl"
type     = { Swap = "Up" }

[[keybindings]]
key      = "L"
modifier = "AltControl"
type     = { Swap = "Right" }

[[keybindings]]
key      = "Plus"
modifier = "Alt"
type     = { Split = "Vertical" }

[[keybindings]]
key      = "Minus"
modifier = "Alt"
type     = { Split = "Horizontal" }

[[keybindings]]
key      = "F"
modifier = "AltControl"
type     = "ToggleFloatingMode"

[[keybindings]]
key      = "F"
modifier = "Alt"
type     = "ToggleFullscreen"

[[keybindings]]
key      = "W"
modifier = "AltControl"
type     = "ToggleWorkMode"

[[keybindings]]
key      = "1"
modifier = "AltShift"
type     = { MoveToWorkspace = 1 }

[[keybindings]]
key      = "2"
modifier = "AltShift"
type     = { MoveToWorkspace = 2 }

[[keybindings]]
key      = "3"
modifier = "AltShift"
type     = { MoveToWorkspace = 3 }

[[keybindings]]
key      = "4"
modifier = "AltShift"
type     = { MoveToWorkspace = 4 }

[[keybindings]]
key      = "1"
modifier = "Alt"
type     = { ChangeWorkspace = 1 }

[[keybindings]]
key      = "2"
modifier = "Alt"
type     = { ChangeWorkspace = 2 }

[[keybindings]]
key      = "3"
modifier = "Alt"
type     = { ChangeWorkspace = 3 }

[[keybindings]]
key      = "4"
modifier = "Alt"
type     = { ChangeWorkspace = 4 }

[[keybindings]]
key      = "5"
modifier = "Alt"
type     = { ChangeWorkspace = 5 }

[[keybindings]]
key      = "Enter"
modifier = "AltControl"
type     = "Absorb"

[[rules]]
manage  = false
pattern = "^(File Explorer|Task Manager)$"

[[rules]]
firefox             = true
has_custom_titlebar = true
pattern             = "^.*- Mozilla Firefox|Mozilla Firefox$"

[[rules]]
has_custom_titlebar = true
pattern             = "^.*- Discord|Discord$"

[[rules]]
has_custom_titlebar = true
pattern             = "^Spotify Premium$"

[[rules]]
chromium            = true
has_custom_titlebar = true
pattern             = "^.*- Google Chrome$"

[[rules]]
chromium            = true
has_custom_titlebar = true
pattern             = "^.*- Visual Studio Code$"
