use bitflags::bitflags;
use winapi::um::winuser::{
	WS_BORDER, WS_CAPTION, WS_CHILD, WS_CHILDWINDOW, WS_CLIPCHILDREN, WS_CLIPSIBLINGS, WS_DISABLED,
	WS_DLGFRAME, WS_GROUP, WS_HSCROLL, WS_ICONIC, WS_MAXIMIZE, WS_MAXIMIZEBOX, WS_MINIMIZE,
	WS_MINIMIZEBOX, WS_OVERLAPPED, WS_OVERLAPPEDWINDOW, WS_POPUP, WS_POPUPWINDOW, WS_SIZEBOX,
	WS_SYSMENU, WS_TABSTOP, WS_THICKFRAME, WS_TILED, WS_TILEDWINDOW, WS_VISIBLE, WS_VSCROLL,
};

bitflags! {
	#[derive(Default)]
	pub struct GwlStyle: i32 {
		const BORDER = WS_BORDER as i32;
		const CAPTION = WS_CAPTION as i32;
		const CHILD = WS_CHILD as i32;
		const CHILDWINDOW = WS_CHILDWINDOW as i32;
		const CLIPCHILDREN = WS_CLIPCHILDREN as i32;
		const CLIPSIBLINGS = WS_CLIPSIBLINGS as i32;
		const DISABLED = WS_DISABLED as i32;
		const DLGFRAME = WS_DLGFRAME as i32;
		const GROUP = WS_GROUP as i32;
		const HSCROLL = WS_HSCROLL as i32;
		const ICONIC = WS_ICONIC as i32;
		const MAXIMIZE = WS_MAXIMIZE as i32;
		const MAXIMIZEBOX = WS_MAXIMIZEBOX as i32;
		const MINIMIZE = WS_MINIMIZE as i32;
		const MINIMIZEBOX = WS_MINIMIZEBOX as i32;
		const OVERLAPPED = WS_OVERLAPPED as i32;
		const OVERLAPPEDWINDOW = WS_OVERLAPPEDWINDOW as i32;
		const POPUP = WS_POPUP as i32;
		const POPUPWINDOW = WS_POPUPWINDOW as i32;
		const SIZEBOX = WS_SIZEBOX as i32;
		const SYSMENU = WS_SYSMENU as i32;
		const TABSTOP = WS_TABSTOP as i32;
		const THICKFRAME = WS_THICKFRAME as i32;
		const TILED = WS_TILED as i32;
		const TILEDWINDOW = WS_TILEDWINDOW as i32;
		const VISIBLE = WS_VISIBLE as i32;
		const VSCROLL = WS_VSCROLL as i32;
	}
}
